OPTIONS http://{{host}}/api
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

{
    "key": "{{my-var}}",
    "k2":"v2"
}

> {%
    client.global.set("password", "Password1!")
%}
