name: 'HTTP tests'

on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: docker run --rm -i -v .:/workdir jetbrains/intellij-http-client -L VERBOSE -r reports -e development -v http-client.env.json req.http

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            reports/**.xml
